services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"  # Vite

